In [1]:
# Import modules
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, classification_report
from sklearn.preprocessing import StandardScaler

In [2]:
#dropped missing data manually since pandas wasn't cooperating
vote_df = pd.read_csv(
    Path('C:/Users/isabe/OneDrive/Documents/GitHub/Project-4/for_lear.csv')   
)
vote_df.head()

,V201228,V201507x,V201549x,V202468x,V202073,V201201,V201151,V201152
0,Republican,37,"White, non-Hispanic","$20,000-24,999",1,Conservative,50,75
1,Democrat,71,"Black, non-Hispanic","$45,000-49,999",0,Conservative,60,15
2,Democrat,56,"Black, non-Hispanic","$20,000-24,999",0,Conservative,80,5
3,Republican,42,Asian or Native Hawaiian/other Pacific Islande...,"$65,000-69,999",1,Liberal,15,80
4,Republican,48,"White, non-Hispanic","$45,000-49,999",0,Conservative,60,30

In [3]:
x = vote_df.drop(columns=['V202073'])
y = vote_df['V202073']

In [4]:
x.head()

,V201228,V201507x,V201549x,V202468x,V201201,V201151,V201152
0,Republican,37,"White, non-Hispanic","$20,000-24,999",Conservative,50,75
1,Democrat,71,"Black, non-Hispanic","$45,000-49,999",Conservative,60,15
2,Democrat,56,"Black, non-Hispanic","$20,000-24,999",Conservative,80,5
3,Republican,42,Asian or Native Hawaiian/other Pacific Islande...,"$65,000-69,999",Liberal,15,80
4,Republican,48,"White, non-Hispanic","$45,000-49,999",Conservative,60,30

In [5]:
#y = y.drop(y[y == -1].index)
y.head()

0    1
1    0
2    0
3    1
4    0
Name: V202073, dtype: int64

In [6]:
x = pd.get_dummies(x)

In [7]:
x.head()

,V201507x,V201151,V201152,V201228_Democrat,V201228_Independent,V201228_Other,V201228_Republican,"V201549x_Asian or Native Hawaiian/other Pacific Islander, non-Hispanic","V201549x_Black, non-Hispanic",V201549x_Hispanic,...,"V202468x_$60,000-64,999","V202468x_$65,000-69,999","V202468x_$70,000-74,999","V202468x_$75,000-79,999","V202468x_$80,000-89,999","V202468x_$90,000-99,999","V202468x_Under $9,999",V201201_Conservative,V201201_Liberal,V201201_Moderate
0,37,50,75,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,71,60,15,True,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
2,56,80,5,True,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
3,42,15,80,False,False,False,True,True,False,False,...,False,True,False,False,False,False,False,False,True,False
4,48,60,30,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [8]:
x.dtypes

V201507x                                                                  int64
V201151                                                                   int64
V201152                                                                   int64
V201228_Democrat                                                           bool
V201228_Independent                                                        bool
V201228_Other                                                              bool
V201228_Republican                                                         bool
V201549x_Asian or Native Hawaiian/other Pacific Islander, non-Hispanic     bool
V201549x_Black, non-Hispanic                                               bool
V201549x_Hispanic                                                          bool
V201549x_Multiple races, non-Hispanic                                      bool
V201549x_Native American/Alaska Native or other race, non-Hispanic         bool
V201549x_White, non-Hispanic                                               bool
V202468x_$10,000-14,999                                                    bool
V202468x_$100,000-109,999                                                  bool
V202468x_$110,000-124,999                                                  bool
V202468x_$125,000-149,999                                                  bool
V202468x_$15,000-19,999                                                    bool
V202468x_$150,000-174,999                                                  bool
V202468x_$175,000-249,999                                                  bool
V202468x_$20,000-24,999                                                    bool
V202468x_$25,000-29,999                                                    bool
V202468x_$250,000 or more                                                  bool
V202468x_$30,000-34,999                                                    bool
V202468x_$35,000-39,999                                                    bool
V202468x_$40,000-44,999                                                    bool
V202468x_$45,000-49,999                                                    bool
V202468x_$50,000-59,999                                                    bool
V202468x_$60,000-64,999                                                    bool
V202468x_$65,000-69,999                                                    bool
V202468x_$70,000-74,999                                                    bool
V202468x_$75,000-79,999                                                    bool
V202468x_$80,000-89,999                                                    bool
V202468x_$90,000-99,999                                                    bool
V202468x_Under $9,999                                                      bool
V201201_Conservative                                                       bool
V201201_Liberal                                                            bool
V201201_Moderate                                                           bool
dtype: object

In [9]:
y.dtypes

dtype('int64')

In [10]:
#optimize random state to get highest r2 we can.
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=55)

In [11]:
scaler = StandardScaler()

# Fit the training data to the standard scaler
x_scaler = scaler.fit(x_train)

# Transform the training data using the scaler
x_train_scaled = x_scaler.transform(x_train)

# Transform the testing data using the scaler
x_test_scaled = x_scaler.transform(x_test)

In [12]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

c:\Users\isabe\anaconda3\envs\dev\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [13]:
r2 = r2_score(y_test,y_pred)
print(r2)

0.7350537634408603

In [14]:
print(model.coef_)

[[-0.01267862 -0.00547679  0.07791929 -1.17835265 -0.62182148  0.35773164
   0.08216467 -0.16054681 -1.02958335 -0.22075941 -0.11045211 -0.08241232
   0.24347618 -0.26191344  1.01291565  0.26735315  0.52147345 -0.27192622
   0.68193045 -0.21814606 -0.07364834 -0.4250685  -0.08179698 -0.66745867
   0.153246    0.23074272 -1.00303706  0.09926488 -0.27398739 -0.10804481
   0.07272828  0.09253638 -0.71568696  0.00183128 -0.3935856  -0.26711137
  -1.18672884  0.09356239]]

In [15]:
print(model.intercept_)

[-2.2387003]